import type { LivestockType, Prisma } from "@prisma/client";
import { prisma } from "../../config/prisma";
import type { NluEntities, NluIntent } from "../../config/mlClient";
import { naira } from "../../utils/format";
import { animalLabel, animals, t, type Lang } from "../../utils/lang";

// Answers to the farmer's questions, worked out from the stored records only. Nothing here is generated by AI,
// so the numbers cannot be invented.

const DAY_MS = 24 * 60 * 60 * 1000;

function capitalize(value: string): string {
  const s = value.replace(/_/g, " ").toLowerCase();
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function startOfMonth(date: Date): Date {
  return new Date(date.getFullYear(), date.getMonth(), 1);
}

function endOfMonth(date: Date): Date {
  return new Date(date.getFullYear(), date.getMonth() + 1, 1);
}

function monthLabel(date: Date): string {
  return date.toLocaleDateString("en-NG", { month: "long", year: "numeric" });
}

function parseDate(raw?: string): Date | null {
  if (!raw) return null;
  const text = raw.trim().toLowerCase();
  if (text === "today") return new Date();
  if (text === "yesterday") return new Date(Date.now() - DAY_MS);
  const parsed = new Date(raw);
  return Number.isNaN(parsed.getTime()) ? null : parsed;
}

interface Period {
  gte: Date;
  lt: Date;
  label: string;
}

function resolvePeriod(raw?: string): Period {
  const base = parseDate(raw) ?? new Date();
  return { gte: startOfMonth(base), lt: endOfMonth(base), label: monthLabel(base) };
}

/** "feed" / "FEED" / "Feed costs" -> "FEED" style key used when expenses are saved. */
function categoryKey(raw?: string): string | undefined {
  if (!raw) return undefined;
  const key = raw.trim().toUpperCase().replace(/[^A-Z0-9]+/g, "_").replace(/^_|_$/g, "");
  return key && key !== "OTHER" ? key : undefined;
}

async function periodExpenseStats(farmId: string, period: Period, scoped: boolean, category?: string) {
  const where: Prisma.ExpenseWhereInput = {
    farmId,
    ...(scoped ? { date: { gte: period.gte, lt: period.lt } } : {}),
    ...(category ? { category: { equals: category, mode: "insensitive" } } : {}),
  };
  const [rows, agg] = await Promise.all([
    prisma.expense.groupBy({ by: ["category"], where, _sum: { amount: true }, _count: { _all: true } }),
    prisma.expense.aggregate({ where, _sum: { amount: true }, _count: { _all: true } }),
  ]);
  return { rows, total: Number(agg._sum.amount ?? 0), count: agg._count._all };
}

async function periodSaleStats(farmId: string, period: Period, scoped: boolean) {
  const where: Prisma.SaleWhereInput = scoped ? { farmId, date: { gte: period.gte, lt: period.lt } } : { farmId };
  const [rows, agg] = await Promise.all([
    prisma.sale.groupBy({ by: ["livestockType"], where, _sum: { amount: true, quantity: true }, _count: { _all: true } }),
    prisma.sale.aggregate({ where, _sum: { amount: true }, _count: { _all: true } }),
  ]);
  return { rows, total: Number(agg._sum.amount ?? 0), count: agg._count._all };
}

const s = (n: number) => (n === 1 ? "" : "s");

async function queryExpenses(farmId: string, entities: NluEntities, lang: Lang): Promise<string> {
  const period = resolvePeriod(entities.date);
  const category = categoryKey(entities.category);
  const what = category ? capitalize(category).toLowerCase() : "";

  let stats = await periodExpenseStats(farmId, period, true, category);
  let label = period.label;

  if (stats.count === 0 && !entities.date) {
    stats = await periodExpenseStats(farmId, period, false, category);
    label = t(lang, "all time", "all time");
  }

  if (stats.count === 0) {
    return category
      ? t(lang, `I can't find any ${what} expenses for ${period.label}.`, `I no see any ${what} expense for ${period.label}.`)
      : t(lang, `I can't find any expenses for ${period.label} yet.`, `I no see any expense wey don enter for ${period.label} yet.`);
  }

  const breakdown = stats.rows
    .sort((a, b) => Number(b._sum.amount ?? 0) - Number(a._sum.amount ?? 0))
    .map((row) => `${capitalize(row.category)}: ${naira(Number(row._sum.amount ?? 0))} (${row._count._all})`)
    .join(", ");

  const subject = category ? t(lang, ` on ${what}`, ` for ${what}`) : "";
  return t(
    lang,
    `For ${label}, you spent ${naira(stats.total)}${subject} across ${stats.count} expense${s(stats.count)}. Breakdown: ${breakdown}.`,
    `For ${label}, you don spend ${naira(stats.total)}${subject} across ${stats.count} expense${s(stats.count)}. Breakdown: ${breakdown}.`
  );
}

async function querySales(farmId: string, entities: NluEntities, lang: Lang): Promise<string> {
  const period = resolvePeriod(entities.date);
  let stats = await periodSaleStats(farmId, period, true);
  let label = period.label;

  if (stats.count === 0 && !entities.date) {
    stats = await periodSaleStats(farmId, period, false);
    label = "all time";
  }

  if (stats.count === 0) {
    return t(
      lang,
      `I can't find any sales for ${period.label} yet.`,
      `I no see any sale wey don enter for ${period.label} yet.`
    );
  }

  const breakdown = stats.rows
    .sort((a, b) => Number(b._sum.amount ?? 0) - Number(a._sum.amount ?? 0))
    .map(
      (row) =>
        `${capitalize(animalLabel(row.livestockType))}: ${naira(Number(row._sum.amount ?? 0))} from ${animals(
          row.livestockType,
          Number(row._sum.quantity ?? 0)
        )} (${row._count._all} sale${s(row._count._all)})`
    )
    .join(", ");

  return t(
    lang,
    `For ${label}, you made ${naira(stats.total)} from ${stats.count} sale${s(stats.count)}. Breakdown: ${breakdown}.`,
    `For ${label}, sales don enter ${naira(stats.total)} from ${stats.count} sale${s(stats.count)}. Breakdown: ${breakdown}.`
  );
}

async function queryProfit(farmId: string, entities: NluEntities, lang: Lang): Promise<string> {
  const period = resolvePeriod(entities.date);
  let expenses = await periodExpenseStats(farmId, period, true);
  let sales = await periodSaleStats(farmId, period, true);
  let label = period.label;

  if (expenses.count === 0 && sales.count === 0 && !entities.date) {
    expenses = await periodExpenseStats(farmId, period, false);
    sales = await periodSaleStats(farmId, period, false);
    label = "all time";
  }

  if (expenses.count === 0 && sales.count === 0) {
    return t(
      lang,
      "I have no sales or expenses recorded yet, so I can't work out your profit. Tell me what you sold or spent.",
      "I never see any sale or expense yet, so I no fit calculate your profit. Tell me wetin you sell or spend."
    );
  }

  const profit = sales.total - expenses.total;
  const verdict =
    profit > 0
      ? t(lang, `You are making a profit of ${naira(profit)}.`, `You dey plus. Net profit na ${naira(profit)}.`)
      : profit < 0
        ? t(
            lang,
            `You are spending more than you earn. Net loss: ${naira(Math.abs(profit))}.`,
            `You dey spend pass wey you take gain. Net loss na ${naira(Math.abs(profit))}.`
          )
        : t(lang, "Sales and expenses are equal, so no profit and no loss.", "Sales and expenses equal, no profit no loss.");

  return `${t(lang, `For ${label}`, `For ${label}`)}: ${t(lang, "Sales", "Sales")} ${naira(sales.total)} (${sales.count}) ${t(
    lang,
    "minus Expenses",
    "minus Expenses"
  )} ${naira(expenses.total)} (${expenses.count}). ${verdict}`;
}

const TYPES: LivestockType[] = ["POULTRY", "GOAT", "SHEEP", "CATTLE", "PIG", "RABBIT", "FISH"];

/** "goat" / "GOATS" / "birds" -> the animal type the question is about, or undefined for "everything". */
function askedType(raw?: string): LivestockType | undefined {
  if (!raw) return undefined;
  const key = raw.trim().toUpperCase();
  if (key === "BIRD" || key === "BIRDS" || key === "CHICKEN" || key === "CHICKENS" || key === "BROILER" || key === "BROILERS")
    return "POULTRY";
  return TYPES.find((t) => key === t || key === `${t}S` || (t === "POULTRY" && key.startsWith("POULTRY")));
}

async function queryLivestock(farmId: string, lang: Lang, rawType?: string): Promise<string> {
  const only = askedType(rawType);
  const [livestockByType, batches, mortalityAgg, healthCount] = await Promise.all([
    prisma.livestock.groupBy({
      by: ["type"],
      where: { farmId, status: "ACTIVE", ...(only ? { type: only } : {}) },
      _sum: { quantity: true },
    }),
    prisma.batch.findMany({
      where: { farmId, status: "ACTIVE", ...(only ? { livestockType: only } : {}) },
      select: { id: true, name: true, quantity: true, livestockType: true },
    }),
    prisma.healthRecord.aggregate({ where: { farmId }, _sum: { mortality: true } }),
    prisma.healthRecord.count({ where: { farmId } }),
  ]);

  if (only) {
    const count = livestockByType.reduce((sum, row) => sum + (row._sum.quantity ?? 0), 0);
    const word = animals(only, count);
    return count > 0
      ? t(lang, `You have ${word}.`, `You get ${word}.`)
      : t(lang, `I can't find any ${animalLabel(only)} on this farm.`, `I no see any ${animalLabel(only)} for this farm.`);
  }

  const lines: string[] = [];
  const present = livestockByType.filter((row) => (row._sum.quantity ?? 0) > 0);
  const parts = present.map((row) => animals(row.type, row._sum.quantity ?? 0));
  const total = present.reduce((sum, row) => sum + (row._sum.quantity ?? 0), 0);

  lines.push(
    total > 0
      ? t(lang, `You have ${total} animals: ${parts.join(", ")}.`, `You get ${total} animals alive: ${parts.join(", ")}.`)
      : t(lang, "I can't find any active animals on this farm.", "I no see any active animal for this farm.")
  );

  if (batches.length > 0) {
    lines.push(
      `${t(lang, "Active batches", "Active batches")}: ${batches
        .map((b) => `${b.name} (${animals(b.livestockType, b.quantity)})`)
        .join(", ")}.`
    );
  }

  const mortality = mortalityAgg._sum.mortality ?? 0;
  lines.push(
    t(
      lang,
      `Deaths recorded so far: ${mortality} (from ${healthCount} health record${s(healthCount)}).`,
      `Mortality wey don enter so far: ${mortality} (from ${healthCount} health record${s(healthCount)}).`
    )
  );

  return lines.join("\n");
}

export async function runQuery(
  farmId: string,
  intent: NluIntent,
  entities: NluEntities,
  lang: Lang
): Promise<string> {
  switch (intent) {
    case "QUERY_EXPENSES":
      return queryExpenses(farmId, entities, lang);
    case "QUERY_SALES":
      return querySales(farmId, entities, lang);
    case "QUERY_PROFIT":
      return queryProfit(farmId, entities, lang);
    case "QUERY_LIVESTOCK":
      return queryLivestock(farmId, lang, entities.livestock_type);
    default:
      return t(
        lang,
        "I can't answer that kind of question yet. Ask me about expenses, sales, profit, or your animals.",
        "I no get that question type yet. Ask me about expenses, sales, profit, or your animals."
      );
  }
}
